MODEL:
  VID:
    ENABLE: True
    METHOD: "cvc_stft"
    STFT:
      MIN_OFFSET: -9
      MAX_OFFSET: 9
#      TRAIN_REF_NUM: 2
      TRAIN_REF_NUM: 4
      TEST_REF_NUM: 10
  META_ARCHITECTURE: "GeneralizedRCNNSTFT"
  RPN_ONLY: True
  FCOS_ON: True
  STFT_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: False
    DEFORMABLE_GROUPS: 1
    STAGE_WITH_GCB: (False, True, True, True)
  RETINANET:
    USE_C5: False
  FCOS:
    NUM_CLASSES: 3
    FPN_STRIDES: [8, 16, 32, 64, 128]
    INFERENCE_TH: 0.05
    NMS_TH: 0.6
    PRE_NMS_TOP_N: 1000
    NORM_REG_TARGETS: True
    CENTERNESS_ON_REG: True
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
  STFT:
    OFFSET_WEIGHT_STD: 0.01
    IOU_THRESH: 0.1
    BBOX_STD: [0.5, 0.5, 0.5, 0.5]
    REG_BETA: 0.11
DATASETS:
  TRAIN: ("CVCVideo_train_videos",)
  TEST: ("CVCVideo_val_videos",)
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 640
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
######## 1 gpu
#SOLVER:
#  BASE_LR: 0.0000125
#  WEIGHT_DECAY: 0.0005
#  IMS_PER_BATCH: 1
#  WARMUP_METHOD: "linear"
#  WARMUP_ITERS: 8000
#  CHECKPOINT_PERIOD: 2000
#  TEST_PERIOD: 0
#  MAX_ITER: 96100
#  LR_TYPE: "step"
#  GAMMA: 0.5
#  STEPS: (64000, 80000, 88000)
######## 4 gpus
SOLVER:
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "linear"
  WARMUP_ITERS: 2000
  CHECKPOINT_PERIOD: 500
  TEST_PERIOD: 0
  MAX_ITER: 24100
  LR_TYPE: "step"
  GAMMA: 0.5
  STEPS: (16000, 20000, 22000)
TEST:
  IMS_PER_BATCH: 4
  DETECTIONS_PER_IMG: 300
